In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\hp\desktop\pandas\.venv\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\hp\desktop\pandas\.venv\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\desktop\pandas\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\desktop\pandas\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\desktop\pandas\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

In [4]:
labels =['a','b','c']
my_list = [10,20,30]

arr = np.array([10,20,30])
dic = {1:10,2:20,3:30}

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(my_list,index = ['a','b','c'])

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(my_list,index = labels)

a    10
b    20
c    30
dtype: int64

In [8]:
data = {"name" : ["john", "anna", "peter", "linda"] , "age" : [28,34,29,42] , "city" : ["new york", "paris", "berlin", "london"] , "salary" : [65000, 70000,62000,85000]}

df = pd.DataFrame(data)
df

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [9]:
data_list = [["john", 28, "new york", 65000], 
             [ "anna", 34,"paris", 70000],
             ["peter", 28, "berlin" , 62000],
             ["linda", 42, "london", 42000]]

pd.DataFrame(data_list)

       0   1         2      3
0   john  28  new york  65000
1   anna  34     paris  70000
2  peter  28    berlin  62000
3  linda  42    london  42000

In [10]:
col = ["name", " age" , " city", "salary"]

In [11]:
df2 = pd.DataFrame(data_list, columns = col)

In [12]:
df2

    name   age      city  salary
0   john    28  new york   65000
1   anna    34     paris   70000
2  peter    28    berlin   62000
3  linda    42    london   42000

In [13]:
df2["name"]

0     john
1     anna
2    peter
3    linda
Name: name, dtype: str

In [14]:
df2["destination"] = ["doctor","eng.", " doctor", "engineer"]

In [15]:
df2

    name   age      city  salary destination
0   john    28  new york   65000      doctor
1   anna    34     paris   70000        eng.
2  peter    28    berlin   62000      doctor
3  linda    42    london   42000    engineer

In [16]:
df2.drop('destination', axis = 1)

    name   age      city  salary
0   john    28  new york   65000
1   anna    34     paris   70000
2  peter    28    berlin   62000
3  linda    42    london   42000

In [17]:
df2

    name   age      city  salary destination
0   john    28  new york   65000      doctor
1   anna    34     paris   70000        eng.
2  peter    28    berlin   62000      doctor
3  linda    42    london   42000    engineer

In [18]:
df2.drop('destination', axis = 1,inplace = True)

In [19]:
df

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [20]:
df.loc[[0,1]]

   name  age      city  salary
0  john   28  new york   65000
1  anna   34     paris   70000

In [21]:
df.iloc[3]

name       linda
age           42
city      london
salary     85000
Name: 3, dtype: object

In [22]:
df.loc[[0,1],["city","age"]]

       city  age
0  new york   28
1     paris   34

In [23]:
# only want to see age of above 30
df[df["age"] > 40]

    name  age    city  salary
3  linda   42  london   85000

In [24]:
# only peaple whose age is above 80 and city paris
df[(df["age"] > 30) & (df["city"] == "paris")]

   name  age   city  salary
1  anna   34  paris   70000

In [25]:
# find missing data

In [26]:
data = {
   'A' : [1,2,np.nan,4,5],
   'B' : [np.nan, 2,3,4,5],
   'c' : [1,2,np.nan,np.nan,5],
   'd' : [np.nan, 2,3,np.nan,5]
}

df = pd.DataFrame(data)
df

     A    B    c    d
0  1.0  NaN  1.0  NaN
1  2.0  2.0  2.0  2.0
2  NaN  3.0  NaN  3.0
3  4.0  4.0  NaN  NaN
4  5.0  5.0  5.0  5.0

In [27]:
df.isna().sum()

A    1
B    1
c    2
d    2
dtype: int64

In [28]:
df.isna()

       A      B      c      d
0  False   True  False   True
1  False  False  False  False
2   True  False   True  False
3  False  False   True   True
4  False  False  False  False

In [29]:
df.isna().any()

A    True
B    True
c    True
d    True
dtype: bool

In [30]:
df.dropna()

     A    B    c    d
1  2.0  2.0  2.0  2.0
4  5.0  5.0  5.0  5.0

In [31]:
df.dropna(thresh = 3)

     A    B    c    d
1  2.0  2.0  2.0  2.0
4  5.0  5.0  5.0  5.0

In [32]:
df.fillna("parth")

       A      B      c      d
0    1.0  parth    1.0  parth
1    2.0    2.0    2.0    2.0
2  parth    3.0  parth    3.0
3    4.0    4.0  parth  parth
4    5.0    5.0    5.0    5.0

In [33]:
values = {'A' : 200, 'B' : 6678,'c' : 456 , 'd' : 9102}

df.fillna(value= values)

       A       B      c       d
0    1.0  6678.0    1.0  9102.0
1    2.0     2.0    2.0     2.0
2  200.0     3.0  456.0     3.0
3    4.0     4.0  456.0  9102.0
4    5.0     5.0    5.0     5.0

In [34]:
df.fillna(df.mean())

     A    B         c         d
0  1.0  3.5  1.000000  3.333333
1  2.0  2.0  2.000000  2.000000
2  3.0  3.0  2.666667  3.000000
3  4.0  4.0  2.666667  3.333333
4  5.0  5.0  5.000000  5.000000

In [35]:

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Alice", "Bob", "Charlie"]
})

df2 = pd.DataFrame({
    "id": [2, 3, 4],
    "score": [85, 90, 75]
})
pd.merge(df1, df2, on="id", how="inner")

   id     name  score
0   2      Bob     85
1   3  Charlie     90

In [36]:
pd.merge(df1, df2, on="id", how="outer")

   id     name  score
0   1    Alice    NaN
1   2      Bob   85.0
2   3  Charlie   90.0
3   4      NaN   75.0

In [37]:
k= pd.concat([df1,df2])

k.fillna("parth")

   id     name  score
0   1    Alice  parth
1   2      Bob  parth
2   3  Charlie  parth
0   2    parth   85.0
1   3    parth   90.0
2   4    parth   75.0

In [38]:
pd.concat([df1,df2],axis = 1)

   id     name  id  score
0   1    Alice   2     85
1   2      Bob   3     90
2   3  Charlie   4     75

In [39]:

df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

result = pd.concat([df1, df2], axis=0)
print(result)

result = pd.concat([df1, df2], axis=1)
print(result)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8
   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [40]:
df3 = pd.DataFrame({
    'name' : [ 'vansh' ,' once' , 'rashi']
}, index=[1,2,3])

df4 = pd.DataFrame({
    'scorer' : [ 266 ,828 , 290]
}, index=[2,3,4])

In [41]:
df2

   A  B
0  5  7
1  6  8

In [42]:
df3.join(df4)

    name  scorer
1  vansh     NaN
2   once   266.0
3  rashi   828.0

In [43]:
df3 = pd.DataFrame([{
    'name' : [ 'vansh' ,' once' , 'rashi']
}], index=[1,2,3])

df4 = pd.DataFrame([{
    'scorer' : [ 266 ,828 , 290]
}], index=[2,3,4])

df3

                    name
1  [vansh,  once, rashi]
2  [vansh,  once, rashi]
3  [vansh,  once, rashi]

In [44]:
import pandas as pd

data = {
    'category': ['A','B','C','D','A','B','A'],
    'store': ['s1','s2','s1','s1','s2','s1','s2'],
    'sales': [100,120,450,888,988,320,567],
    'quantity': [10,75,12,14,78,24,11],
    'Date': pd.date_range('2026-01-01', periods=7)
}

df = pd.DataFrame(data)
df

  category store  sales  quantity       Date
0        A    s1    100        10 2026-01-01
1        B    s2    120        75 2026-01-02
2        C    s1    450        12 2026-01-03
3        D    s1    888        14 2026-01-04
4        A    s2    988        78 2026-01-05
5        B    s1    320        24 2026-01-06
6        A    s2    567        11 2026-01-07

In [45]:
# group by categories and calculate the sum of sales

cat = df.groupby('category')

for i,v in cat:
    print(i)
    print(v)

A
  category store  sales  quantity       Date
0        A    s1    100        10 2026-01-01
4        A    s2    988        78 2026-01-05
6        A    s2    567        11 2026-01-07
B
  category store  sales  quantity       Date
1        B    s2    120        75 2026-01-02
5        B    s1    320        24 2026-01-06
C
  category store  sales  quantity       Date
2        C    s1    450        12 2026-01-03
D
  category store  sales  quantity       Date
3        D    s1    888        14 2026-01-04

In [46]:
df.groupby('category')['sales'].sum()

category
A    1655
B     440
C     450
D     888
Name: sales, dtype: int64

In [47]:
# group by stores and calculates its sum
df.groupby('store')['sales'].sum()

store
s1    1758
s2    1675
Name: sales, dtype: int64

In [48]:
# group by multiple coulumns
# group by category and store

df.groupby(['category','store'])['sales'].sum()

category  store
A         s1        100
          s2       1555
B         s1        320
          s2        120
C         s1        450
D         s1        888
Name: sales, dtype: int64

In [49]:
k = df['sales'].mean()
print(k)

490.42857142857144

In [50]:
df['sales'].agg(['mean','min','max'])

mean    490.428571
min     100.000000
max     988.000000
Name: sales, dtype: float64

In [51]:

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [52]:
df = pd.DataFrame(data)
df['month'] = df['Date'].dt.month_name()
df['quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

df

         Date Product Region  Sales  Units    Rep    month quarter
0  2023-01-01       A   East    569     25   John  January      Q1
1  2023-01-02       B   West    232     11   Mary  January      Q1
2  2023-01-03       C  North    245     86    Bob  January      Q1
3  2023-01-04       D  South    400     18  Alice  January      Q1
4  2023-01-05       A   East    981     60   John  January      Q1
5  2023-01-06       B   West    676     81   Mary  January      Q1
6  2023-01-07       C  North    498     58    Bob  January      Q1
7  2023-01-08       D  South    871     66  Alice  January      Q1
8  2023-01-09       A   East    128     14   John  January      Q1
9  2023-01-10       B   West    118     14   Mary  January      Q1
10 2023-01-11       C  North    282     58    Bob  January      Q1
11 2023-01-12       D  South    521     40  Alice  January      Q1
12 2023-01-13       A   East    498     60   John  January      Q1
13 2023-01-14       B   West    289     21   Mary  January      Q1
14 2023-01-15       C  North    327     93    Bob  January      Q1
15 2023-01-16       D  South    720     53  Alice  January      Q1
16 2023-01-17       A   East    999     20   John  January      Q1
17 2023-01-18       B   West    409     10   Mary  January      Q1
18 2023-01-19       C  North    181     96    Bob  January      Q1
19 2023-01-20       D  South    242     38  Alice  January      Q1

In [53]:
pd.pivot_table(df,values= 'Sales',index= 'Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     569.0    NaN    NaN    NaN
North      NaN    NaN  282.0    NaN
South      NaN    NaN    NaN  521.0
West       NaN  289.0    NaN    NaN

In [54]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [55]:
df1 = {
    'a' : [1,2,3],
    'b' : [10,20,30],
    'c' : [100,200,300]}

f = pd.DataFrame(df1)
f

   a   b    c
0  1  10  100
1  2  20  200
2  3  30  300

In [56]:
f.shape

(3, 3)

In [57]:
f.columns

Index(['a', 'b', 'c'], dtype='str')

In [58]:
f.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [59]:
f.describe()

         a     b      c
count  3.0   3.0    3.0
mean   2.0  20.0  200.0
std    1.0  10.0  100.0
min    1.0  10.0  100.0
25%    1.5  15.0  150.0
50%    2.0  20.0  200.0
75%    2.5  25.0  250.0
max    3.0  30.0  300.0

In [60]:
f['a']+10

0    11
1    12
2    13
Name: a, dtype: int64

In [ ]:
df1 = {
    'a' : [1,2,3],
    'b' : [10,20,30],
    'c' : [100,200,300]}

f = pd.DataFrame(df1)

f['b'] = f["b"].apply(lambda x: x**2)

f

   a    b    c
0  1  100  100
1  2  400  200
2  3  900  300

In [76]:
pd.read_csv(r"anime.csv")

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71